CREATE TABLE IF NOT EXISTS beds (
    id SERIAL PRIMARY KEY,
    bed_id_str VARCHAR(50) UNIQUE NOT NULL,
    ward_name VARCHAR(50) NOT NULL,
    type VARCHAR(30) NOT NULL,
    -- ICU, VENTILATOR, GENERAL, SEMI-PRIVATE
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    -- AVAILABLE, OCCUPIED, MAINTENANCE
    patient_id VARCHAR(50) REFERENCES patients(patient_id_str),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);